### ISSUE TITLE
Is it time to merge weak announcement support to the main branch?

### ISSUE THREAD

**Issue by martinmcclure** [GemTalk/Announcements#3]
Weak support was added nine months ago -- I've been using it pretty much ever since. Is there any work to be done before merging it to the main branch for the upcoming alpha?

**Comment by kurtkilpela** [comment]
See https://github.com/GemTalk/Announcements/pull/2

**Comment by kurtkilpela** [comment]
It seems the merge occurred and the topic branch changes were in development and main. I removed the topic branch.
